# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 05:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0004_auto_20161121_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='introduce',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collect',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 21, 13, 6, 37, 996981)),
        ),
        migrations.AlterField(
            model_name='houseinfo',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='houseinfo',
            name='circum',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='houseinfo',
            name='community',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='houseinfo',
            name='house',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='houseinfo',
            name='houseIntroduce',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='houseinfo',
            name='housetype',
            field=models.CharField(blank=True, choices=[('三室一厅两卫', '三室一厅两卫'), ('四室两厅两卫', '四室两厅两卫'), ('三室两厅两卫', '三室两厅两卫'), ('三室一厅一卫', '三室一厅一卫'), ('二室一厅一卫', '二室一厅一卫'), ('一室一厅一卫', '一室一厅一卫')], max_length=200),
        ),
        migrations.AlterField(
            model_name='houseinfo',
            name='installations',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='houseinfo',
            name='label',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='houseinfo',
            name='pic_1',
            field=models.ImageField(blank=True, upload_to='house_pic'),
        ),
        migrations.AlterField(
            model_name='houseinfo',
            name='pic_2',
            field=models.ImageField(blank=True, upload_to='house_pic'),
        ),
        migrations.AlterField(
            model_name='houseinfo',
            name='pic_3',
            field=models.ImageField(blank=True, upload_to='house_pic'),
        ),
        migrations.AlterField(
            model_name='houseinfo',
            name='pic_4',
            field=models.ImageField(blank=True, upload_to='house_pic'),
        ),
        migrations.AlterField(
            model_name='houseinfo',
            name='pic_5',
            field=models.ImageField(blank=True, upload_to='house_pic'),
        ),
        migrations.AlterField(
            model_name='houseinfo',
            name='pic_6',
            field=models.ImageField(blank=True, upload_to='house_pic'),
        ),
        migrations.AlterField(
            model_name='houseinfo',
            name='pic_7',
            field=models.ImageField(blank=True, upload_to='house_pic'),
        ),
        migrations.AlterField(
            model_name='houseinfo',
            name='pic_8',
            field=models.ImageField(blank=True, upload_to='house_pic'),
        ),
        migrations.AlterField(
            model_name='houseinfo',
            name='pic_9',
            field=models.ImageField(blank=True, upload_to='house_pic'),
        ),
        migrations.AlterField(
            model_name='houseinfo',
            name='translate',
            field=models.TextField(blank=True, default=''),
        ),
    ]
