# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 17:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0008_auto_20161121_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseinfo',
            name='pic_index',
            field=models.ImageField(blank=True, upload_to='house_pic'),
        ),
        migrations.AddField(
            model_name='houseinfo',
            name='pic_list',
            field=models.ImageField(blank=True, upload_to='house_pic'),
        ),
        migrations.AlterField(
            model_name='collect',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 22, 1, 3, 9, 591667)),
        ),
        migrations.AlterField(
            model_name='houseinfo',
            name='housetype',
            field=models.CharField(blank=True, choices=[('一室一厅一卫', '一室一厅一卫'), ('二室一厅一卫', '二室一厅一卫'), ('三室一厅两卫', '三室一厅两卫'), ('三室两厅两卫', '三室两厅两卫'), ('四室两厅两卫', '四室两厅两卫'), ('三室一厅一卫', '三室一厅一卫')], max_length=200),
        ),
    ]
