# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0017_auto_20161123_0021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collect',
            name='datetime',
        ),
        migrations.AddField(
            model_name='collect',
            name='date',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='collect',
            name='time',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='houseinfo',
            name='housetype',
            field=models.CharField(blank=True, choices=[('一室一厅一卫', '一室一厅一卫'), ('三室两厅两卫', '三室两厅两卫'), ('四室两厅两卫', '四室两厅两卫'), ('三室一厅两卫', '三室一厅两卫'), ('二室一厅一卫', '二室一厅一卫'), ('三室一厅一卫', '三室一厅一卫')], max_length=200),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='sex',
            field=models.CharField(choices=[('保密', '保密'), ('男', '男'), ('女', '女')], default='保密', max_length=10),
        ),
    ]
