# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0018_auto_20161123_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='collect',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='houseinfo',
            name='housetype',
            field=models.CharField(blank=True, choices=[('三室一厅一卫', '三室一厅一卫'), ('三室两厅两卫', '三室两厅两卫'), ('一室一厅一卫', '一室一厅一卫'), ('四室两厅两卫', '四室两厅两卫'), ('三室一厅两卫', '三室一厅两卫'), ('二室一厅一卫', '二室一厅一卫')], max_length=200),
        ),
    ]
